name: Print the context of events in git

on:
  push:
    branches:
      - main

jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub Event Context
        env:
          EVENT_CONTEXT: ${{ tojson(github.event) }}
        run: |
          echo "$EVENT_CONTEXT"
